MONGO_URI: mongodb+srv://venkatesan2001official:venkatesan2001official@cluster0.we3z6ih.mongodb.net/"
PORT: 8000
HASH_SECRET_KEY: HASH_SECRET_KEY
STAGE: DEV
JWT_SECRET_KEY: JWT_SECRET_KEY
JWT_EXPIRATION_TIME: 3600
